project:
  type: book
  output-dir: docs
  
book:
  title: "<i class='fas fa-bug' style='color: #2F855A;'></i> Caderno de Aulas: Análise e Visualização de Dados em Fitopatologia" # Ícone de inseto (bug) adicionado aqui
  author: "Letícia Caroline"
  date: "01/07/2025"
  chapters:
    - Início.qmd
    - index.qmd
    - 01-intro.qmd
    - 02-Capítulo.qmd
    - Conclusão.qmd
    - references.qmd
    - Fim.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: custom.css
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
  pdf:
    documentclass: scrreprt

editor: visual

execute:
  message: false
  warning: false
